<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerFZxXUem\srcDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerFZxXUem/srcDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerFZxXUem.legacy');

    return;
}

if (!\class_exists(srcDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerFZxXUem\srcDevDebugProjectContainer::class, srcDevDebugProjectContainer::class, false);
}

return new \ContainerFZxXUem\srcDevDebugProjectContainer(array(
    'container.build_hash' => 'FZxXUem',
    'container.build_id' => '1d4dad1e',
    'container.build_time' => 1541684647,
), __DIR__.\DIRECTORY_SEPARATOR.'ContainerFZxXUem');
