<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerOaYMQOA\srcDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerOaYMQOA/srcDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerOaYMQOA.legacy');

    return;
}

if (!\class_exists(srcDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerOaYMQOA\srcDevDebugProjectContainer::class, srcDevDebugProjectContainer::class, false);
}

return new \ContainerOaYMQOA\srcDevDebugProjectContainer(array(
    'container.build_hash' => 'OaYMQOA',
    'container.build_id' => '53b4d666',
    'container.build_time' => 1542014509,
), __DIR__.\DIRECTORY_SEPARATOR.'ContainerOaYMQOA');
